services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi
    container_name: fastapi-backend
    command: uvicorn src.backend.main:app --host 0.0.0.0 --port 8081
    volumes:
      - .:/app
    ports:
      - "40161:8081"
    environment:
      - ENV=development